### ISSUE TITLE
Testing GitHub Markdown - Task List

### ISSUE THREAD

**Issue by jwgoh** [jwgoh/Blah#3]
- [ ] Nested task list in a task list
  - [x] This works

- Nested task list in a list
  - [x] This works

### Task list after header

- [x] This works

### Nested task list in a task list after header
- [ ] Nested task list in a task list
  - [ ] This works

### Nested task list in a list after header
- Nesting task list in a list
  - [ ] This *DOESN'T* work
